name: CI Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-test-lint:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:20.10.7
        options: --privileged

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r ci/requirements.txt

    - name: Lint with Black
      run: |
        echo "Running black..."
        black --check app

    - name: Run Pytest
      run: |
        echo "Running pytest..."
        pytest

    - name: Docker build check
      run: |
        echo "Building Docker image..."
        docker build -t incident-bot-test .